from enum import *

class PosizioneMilitare(StrEnum):

    Soldato = auto()
    Caporale = auto()
    Caporale_Maggiore = auto()
    Graduato = auto()
    Graduato_Scelto = auto()
    Graduato_Capo = auto()
    Primo_Graduato = auto()
    Graduato_Aiutante = auto() 
    Sergente = auto()
    Sergente_Maggiore = auto()
    Sergente_Maggiore_Capo = auto()
    Sergente_Maggiore_Aiutante = auto()
    Maresciallo = auto()
    Maresciallo_Ordinario = auto()
    Maresciallo_Capo = auto()
    Primo_Maresciallo = auto()
    Luogotenente = auto()
    Primo_Luogotenente = auto()
    Sottotenente = auto()
    Tenente = auto()
    Capitano = auto()
    Maggiore = auto()
    Tenente_Colonnello = auto()
    Colonnello = auto()
    Generale_di_Brigata = auto()
    Generale_di_Divisione = auto()
    Generale_di_Corpo_di_Armata = auto()